#!/usr/bin/perl
#
# This script is used to convert perTargetCoverage files generated by Picard HsMetrics
# into input files for the exomeCNV R package
#
use strict;
use warnings;

my $inputFile = shift || die("Usage: perl $0 <perTargetCoverage file>\n");
open(IN, "<", $inputFile) || die("Unable to open input file $inputFile\n");
print "probe\tchr\tprobe_start\tprobe_end\ttargeted base\tsequenced base\tcoverage\taverage coverage\tbase with >10 coverage\n";
while (my $line = <IN>) {
	next if 1..1;
	my ($chrom, $start, $end, $length, $name, $percentgc, $mean_coverage, $normalized_coverage)
	= split(/\t/, $line);
	
	print $name."\t";					# probe
	print $chrom."\t";					# chr
	print $start."\t";					# probe start
	print $end."\t";					# probe end
	print $length."\t";					# targeted base
	print $length."\t";					# sequenced base. This value isn't taken into account.
	print $length*$mean_coverage."\t";	# coverage
	print $mean_coverage."\t";			# average coverage
	print $length."\n";					# base with >10 coverage. This value isn't taken into account.
	
}
close(IN);