#!/usr/bin/perl
#
# This script is used to convert multiple perTargetCoverage files generated by Picard HsMetrics
# into one pooled input file for the exomeCNV R package
#
use strict;
use warnings;
use Scalar::Util qw(looks_like_number);

if (!@ARGV) { die("Usage: perl $0 <input file 1> ... <input file n>\n"); }
my @inputFiles = @ARGV;
my $nbSamples = $#inputFiles + 1;

my %pool;
my $i = 0;

print "probe\tchr\tprobe_start\tprobe_end\ttargeted base\tsequenced base\tcoverage\taverage coverage\tbase with >10 coverage\n";


foreach my $inputFile (@inputFiles) {
	$i++;
	open(IN, "<", $inputFile) || die("Unable to open input file $inputFile\n");
	readline(IN);	# skip first line
	while (my $line = <IN>) {
		chomp($line);
		my ($chrom, $start, $end, $length, $name, $percentgc, $mean_coverage, $normalized_coverage)
		= split(/\t/, $line);

		if (!$pool{$name}) { $pool{$name} = $length*$mean_coverage; } else {
			$pool{$name} += $length*$mean_coverage;
		}

		if ($i == $#inputFiles) {	# last array element

			my $coverage =  sprintf("%.3f", $pool{$name} / $i);
			my $meanCov = sprintf("%.3f", $coverage / $length);

			print $name."\t";					# probe
			print $chrom."\t";					# chr
			print $start."\t";					# probe start
			print $end."\t";					# probe end
			print $length."\t";					# targeted base
			print $length."\t";					# sequenced base. This value isn't taken into account.
			print $coverage."\t";				# coverage
			print $meanCov."\t";				# average coverage
			print $length."\n";					# base with >10 coverage. This value isn't taken into account.
		}
	}
}
