#!/usr/bin/perl
#
# This script parses a VCF file generated by GATK and
# only keeps PASS records
#

use strict;
use warnings;

my $file = shift;
if (!$file || !-f $file) {	die("usage: perl $0 <VCF file>\n"); }

open(IN, "<", $file);
while (my $line = <IN>) {
	if ($line =~ /^#/) { 
		print $line; 
	} elsif ($line =~ /PASS/) {
		print $line;
	}
}
close(IN);
