#!/usr/bin/perl
#
# This script parses the json query generated by the R TCGABiolinks package
# This allows to extract the correspondance between 
# - sample id (what I call the short sdubmitter id) which is used in the clinical data table
# - file name 
#
use strict;
use warnings;
use v5.10;

use JSON::MaybeXS;
use Path::Tiny;
use Data::Dumper;

my $jsonFile = path("query.json"); 
my $jsonInput = $jsonFile->slurp;
my $jsonHash = decode_json($jsonInput);

my $arrayRef = $jsonHash->{'data'}->{'hits'};
my @hits = @{ $arrayRef };

for my $hit (@hits) {
	my $dataType = $hit->{"data_type"};
	next if $dataType ne "Gene Expression Quantification";

	my $fileId = $hit->{"file_id"};
	my $fileName = $hit->{"file_name"};
	my $workflowType = $hit->{"analysis"}->{"workflow_type"};
	next if $workflowType ne "HTSeq - Counts";

	my $submitterId = $hit->{'cases'}[0]->{'samples'}[0]->{'portions'}[0]->{'analytes'}[0]->{'aliquots'}[0]->{'submitter_id'};

	my $shortSubmitterId = substr($submitterId, 0, 12);

	my $oldFile = "HTSeq-Counts/$fileId/$fileName";
	my $newFile = "htseq/$shortSubmitterId-htseq.txt.gz";

	say "$fileId/$fileName\t$shortSubmitterId";
	system("mv $oldFile $newFile");

}

#->[0]->{"data_type"};


#say Dumper($test);
