# 
# Quick and dirty script to plot the coverage distribution
# generated by Picard CollectHsMetrics, when using the PER_TARGET_COVERAGE option
# 
# Usage: Rscript plotPicardPerTargetCoverage.R <PER_TARGET_COVERAGE file>
#
# Output: a png file with the same base name as the per target coverage file


CLI_args = commandArgs(trailingOnly=TRUE)
ptcFilePath<-CLI_args[1]
pngFilePath<-paste0(tools::file_path_sans_ext(ptcFilePath), ".png")
baseName<-tools::file_path_sans_ext(basename(ptcFilePath))

ptcFile<-read.table(ptcFilePath, header=TRUE)

meanCoverage<-sum(ptcFile$mean_coverage*ptcFile$length)/sum(ptcFile$length)


testTable<-cbind(round(ptcFile$mean_coverage), ptcFile$length)
df<-as.data.frame(testTable)
agregDF<-(aggregate(df, list(df$V1), sum))
agregDF<-agregDF[,-2]
names(agregDF)<-c("coverage", "nbBases")

percent10X<-sum(agregDF[agregDF$coverage>=10, "nbBases"])/sum(agregDF$nbBases)
percent20X<-sum(agregDF[agregDF$coverage>=20, "nbBases"])/sum(agregDF$nbBases)
percent30X<-sum(agregDF[agregDF$coverage>=30, "nbBases"])/sum(agregDF$nbBases)
percent40X<-sum(agregDF[agregDF$coverage>=40, "nbBases"])/sum(agregDF$nbBases)
percent50X<-sum(agregDF[agregDF$coverage>=50, "nbBases"])/sum(agregDF$nbBases)


xPlotPosition<-median(agregDF$coverage)*1.3
yPlotPosition<-max(agregDF$nbBases)*0.8

png(file=pngFilePath, width = 1200, height = 700, res = 150, units = "px",)
barplot(agregDF$nbBases, names.arg = agregDF$coverage, col="light blue", main=paste("Coverage distribution for", baseName))
text(xPlotPosition, yPlotPosition, paste("mean coverage:", round(meanCoverage, 2)), adj=0)
text(xPlotPosition, yPlotPosition*0.8, paste("bases >= 10X:", round(percent10X*100, 2), "%"), adj=0)
text(xPlotPosition, yPlotPosition*0.7, paste("bases >= 20X:", round(percent20X*100, 2), "%"), adj=0)
text(xPlotPosition, yPlotPosition*0.6, paste("bases >= 30X:", round(percent30X*100, 2), "%"), adj=0)
text(xPlotPosition, yPlotPosition*0.5, paste("bases >= 40X:", round(percent40X*100, 2), "%"), adj=0)
text(xPlotPosition, yPlotPosition*0.4, paste("bases >= 50X:", round(percent50X*100, 2), "%"), adj=0)
dev.off()
